version: '2'
services:

  mysql:
    container_name: MR-MySQL
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    volumes:
      - ~/Codes/Docker/DockerDatas/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./tiny-mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  redis:
    container_name: MR-Redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
